//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrjHikariwoAnim.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Location_FormMain {
            get {
                return ((global::System.Drawing.Point)(this["Location_FormMain"]));
            }
            set {
                this["Location_FormMain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Location_FormAttribute {
            get {
                return ((global::System.Drawing.Point)(this["Location_FormAttribute"]));
            }
            set {
                this["Location_FormAttribute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Location_FormControl {
            get {
                return ((global::System.Drawing.Point)(this["Location_FormControl"]));
            }
            set {
                this["Location_FormControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Location_FormImageCut {
            get {
                return ((global::System.Drawing.Point)(this["Location_FormImageCut"]));
            }
            set {
                this["Location_FormImageCut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Location_FormImageList {
            get {
                return ((global::System.Drawing.Point)(this["Location_FormImageList"]));
            }
            set {
                this["Location_FormImageList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color BackColor_ColorBack {
            get {
                return ((global::System.Drawing.Color)(this["BackColor_ColorBack"]));
            }
            set {
                this["BackColor_ColorBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGreen")]
        public global::System.Drawing.Color BackColor_ColorGrid {
            get {
                return ((global::System.Drawing.Color)(this["BackColor_ColorGrid"]));
            }
            set {
                this["BackColor_ColorGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.Drawing.Color BackColor_ColorCross {
            get {
                return ((global::System.Drawing.Color)(this["BackColor_ColorCross"]));
            }
            set {
                this["BackColor_ColorCross"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Checked_DrawGird {
            get {
                return ((bool)(this["Checked_DrawGird"]));
            }
            set {
                this["Checked_DrawGird"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Checked_DrawCross {
            get {
                return ((bool)(this["Checked_DrawCross"]));
            }
            set {
                this["Checked_DrawCross"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal Value_WidthGrid {
            get {
                return ((decimal)(this["Value_WidthGrid"]));
            }
            set {
                this["Value_WidthGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Checked_GridSnap {
            get {
                return ((bool)(this["Checked_GridSnap"]));
            }
            set {
                this["Checked_GridSnap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Checked_ImageList {
            get {
                return ((bool)(this["Checked_ImageList"]));
            }
            set {
                this["Checked_ImageList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Checked_Control {
            get {
                return ((bool)(this["Checked_Control"]));
            }
            set {
                this["Checked_Control"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Checked_Attribute {
            get {
                return ((bool)(this["Checked_Attribute"]));
            }
            set {
                this["Checked_Attribute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Checked_CellList {
            get {
                return ((bool)(this["Checked_CellList"]));
            }
            set {
                this["Checked_CellList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color FormRateGraph_BackColor {
            get {
                return ((global::System.Drawing.Color)(this["FormRateGraph_BackColor"]));
            }
            set {
                this["FormRateGraph_BackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DeepSkyBlue")]
        public global::System.Drawing.Color FormRateGraph_GraphColor {
            get {
                return ((global::System.Drawing.Color)(this["FormRateGraph_GraphColor"]));
            }
            set {
                this["FormRateGraph_GraphColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FormRateGraph_DrawGrid {
            get {
                return ((bool)(this["FormRateGraph_DrawGrid"]));
            }
            set {
                this["FormRateGraph_DrawGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGreen")]
        public global::System.Drawing.Color FormRateGraph_ColorGrid {
            get {
                return ((global::System.Drawing.Color)(this["FormRateGraph_ColorGrid"]));
            }
            set {
                this["FormRateGraph_ColorGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color FormRateGraph_LineColor {
            get {
                return ((global::System.Drawing.Color)(this["FormRateGraph_LineColor"]));
            }
            set {
                this["FormRateGraph_LineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color FormRateGraph_ColorCurrent {
            get {
                return ((global::System.Drawing.Color)(this["FormRateGraph_ColorCurrent"]));
            }
            set {
                this["FormRateGraph_ColorCurrent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastImageDirectory {
            get {
                return ((string)(this["LastImageDirectory"]));
            }
            set {
                this["LastImageDirectory"] = value;
            }
        }
    }
}
